<Project Sdk="Microsoft.NET.Sdk.Razor">

	<PropertyGroup>
		<OutputType>WinExe</OutputType>
		<TargetFramework>net9.0-windows7.0</TargetFramework>
		<Nullable>enable</Nullable>
		<UseWindowsForms>true</UseWindowsForms>
		<ImplicitUsings>enable</ImplicitUsings>
		<RootNamespace>SolutionExplorer.KMS.WinUI</RootNamespace>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.AspNetCore.Components.WebView.WindowsForms" Version="9.0.100" />
		<PackageReference Include="Microsoft.Extensions.Hosting" Version="9.0.8" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\SolutionExplorer.KMS.SharedUI\SolutionExplorer.KMS.SharedUI.csproj" />
	</ItemGroup>

	<ItemGroup>
		<Content Update="wwwroot\index.html">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
	</ItemGroup>

</Project>